/**
 * Code Coverage for imported wsdl DocuSingAPI
 *
 * 
 * Author: antonio.bravo@golligo.co.uk
 * ab
 **/
@isTest
public with sharing class DocuSignAPITest{

	@isTest(seeAllData=false)
	static void DocuSignAPI_CodeCoverage (){

		new DocuSignAPI.SSN4InformationInput();
	    new DocuSignAPI.EventNotification();
	    new DocuSignAPI.ArrayOfServerTemplate();
	    new DocuSignAPI.ArrayOfTemplateReferenceFieldDataDataValue();
	    new DocuSignAPI.CreateEnvelopeResponse_element();
	    new DocuSignAPI.SendEnvelopeResponse_element();
	    new DocuSignAPI.ArrayOfTemplateReferenceRoleAssignment();
	    new DocuSignAPI.Attachment();
	    new DocuSignAPI.SSN4Information();
	    new DocuSignAPI.IDCheckInformation();
	    new DocuSignAPI.Document();
	    new DocuSignAPI.ArrayOfTemplateReference();
	    new DocuSignAPI.RecipientStatus();
	    new DocuSignAPI.ArrayOfCompositeTemplate();
	    new DocuSignAPI.CreateEnvelope_element();
	    new DocuSignAPI.Reminders();
	    new DocuSignAPI.CreateEnvelopeFromTemplates_element();
	    new DocuSignAPI.ArrayOfCustomField();
	    new DocuSignAPI.ArrayOfRecipient1();
	    new DocuSignAPI.FormData();
	    new DocuSignAPI.ArrayOfTab();
	    new DocuSignAPI.RequestRecipientToken_element();
	    new DocuSignAPI.EnvelopeEvent();
	    new DocuSignAPI.Recipient();
	    new DocuSignAPI.FormDataXfdf();
	    new DocuSignAPI.RecipientCaptiveInfo();
	    new DocuSignAPI.ArrayOfRecipientStatus();
	    new DocuSignAPI.AuthenticationStatus();
	    new DocuSignAPI.ArrayOfFormDataXfdfField();
	    new DocuSignAPI.RecipientPhoneAuthentication();
	    new DocuSignAPI.TemplateReferenceFieldDataDataValue();
	    new DocuSignAPI.CreateEnvelopeFromTemplatesAndFormsResponse_element();
	    new DocuSignAPI.ArrayOfString1();
	    new DocuSignAPI.ArrayOfDocumentStatus();
	    new DocuSignAPI.CreateEnvelopeFromTemplatesResponse_element();
	    new DocuSignAPI.SendEnvelope_element();
	    new DocuSignAPI.RequestRecipientFaxToken_element();
	    new DocuSignAPI.DOBInformationInput();
	    new DocuSignAPI.RequestSenderTokenResponse_element();
	    new DocuSignAPI.InlineTemplate();
	    new DocuSignAPI.RecipientSignatureInfo();
	    new DocuSignAPI.AddressInformationInput();
	    new DocuSignAPI.ArrayOfRecipient();
	    new DocuSignAPI.CreateEnvelopeFromTemplatesAndForms_element();
	    new DocuSignAPI.EnvelopeInformation();
	    new DocuSignAPI.AddressInformation();
	    new DocuSignAPI.ArrayOfTabStatus();
	    new DocuSignAPI.TemplateReferenceRoleAssignment();
	    new DocuSignAPI.ArrayOfDocument();
	    new DocuSignAPI.Envelope();
	    new DocuSignAPI.ArrayOfAttachment();
	    new DocuSignAPI.Notification();
	    new DocuSignAPI.RequestSenderToken_element();
	    new DocuSignAPI.CreateAndSendEnvelopeResponse_element();
	    new DocuSignAPI.RequestRecipientTokenAuthenticationAssertion();
	    new DocuSignAPI.SSN9InformationInput();
	    new DocuSignAPI.ServerTemplate();
	    new DocuSignAPI.RequestRecipientTokenResponse_element();
	    new DocuSignAPI.IDCheckInformationInput();
	    new DocuSignAPI.TabStatus();
	    new DocuSignAPI.ArrayOfMatchBox();
	    new DocuSignAPI.SSN9Information();
	    new DocuSignAPI.EnvelopeStatus();
	    new DocuSignAPI.ArrayOfEnvelopeEvent();
	    new DocuSignAPI.MatchBox();
	    new DocuSignAPI.TemplateReferenceFieldData();
	    new DocuSignAPI.TemplateReference();
	    new DocuSignAPI.CompositeTemplate();
	    new DocuSignAPI.DOBInformation();
	    new DocuSignAPI.DocumentStatus();
	    new DocuSignAPI.AnchorTab();
	    new DocuSignAPI.EventResult();
	    new DocuSignAPI.FormDataXfdfField();
	    new DocuSignAPI.PDFMetaDataTemplate();
	    new DocuSignAPI.Tab();
	    new DocuSignAPI.ArrayOfInlineTemplate();
	    new DocuSignAPI.ArrayOfString();
	    new DocuSignAPI.VaultingDetails();
	    new DocuSignAPI.CustomField();
	    new DocuSignAPI.Expirations();
	    new DocuSignAPI.RecipientStatusEsignAgreementInformation();
	    new DocuSignAPI.VaultingOptions();
	    new DocuSignAPI.RequestRecipientTokenClientURLs();
	    new DocuSignAPI.CreateAndSendEnvelope_element();

	}

}