@isTest
public with sharing class CompanyDetailsControllerTest {

	@isTest static void test_method_one() {
		//CompaniesHouseTestData testData = CompaniesHouseTestData.getInstance();

		//Transaction_Type__mdt testForm = CompaniesHouseTestData.getInstance().testForm;

		//Transaction_Type_Step__mdt testStep1 = CompaniesHouseTestData.getInstance().testStep1;
		//Account testPresenter = CompaniesHouseTestData.getInstance().presenterAccount;

		//Account testCompany = CompaniesHouseTestData.getInstance().companyAccount;

		//// needs mock web callout information here for initialize step test
		//insert testPresenter;

		//insert testCompany;

		//Transaction__c transac = testData.tx;

		//transac.Company__c = testCompany.Id;
		//transac.Valid_Step_Ids__c = testStep1.Id;
		//transac.CompanyNumber__c = '05448736';

		//insert transac;

		//PageReference companydetailstest = Page.Guidance;
		//companydetailstest.getParameters().put('c', SecurityManager.encryptText(transac.Id + AppConstants.ID_DELIM_CHAR + testStep1.Id + AppConstants.ID_DELIM_CHAR + String.valueOf(DateTime.now().getTime())));
		//Test.setCurrentPage(companydetailstest);

		//CompanyDetailsController controller = new CompanyDetailsController();
		//controller.nextAction();
		//controller.previousAction();
	}

	@isTest static void test_method_two() {
		// Implement test code
	}

}