/*
Name:  ISerialisable.cls
Copyright © 2016  Methods Digital
======================================================
======================================================
Purpose:
-------

Simple interface that allows serialisation classes
to be instantiated generically.

======================================================
======================================================
History
------- 
Ver. Author        Date        Detail
1.0  Mark Cane&    2016-02-04  Initial development.
*/
public interface ISerialisable {
	String serialise(); 
}